// Demo seed data used by the admin "Seed marketplace" action.
// Image URLs are bundled assets served from the deployed site.
import villa from "@/assets/asset-villa.jpg";
import penthouse from "@/assets/asset-penthouse.jpg";
import lambo from "@/assets/asset-lambo.jpg";
import ferrari from "@/assets/asset-ferrari.jpg";
import yacht from "@/assets/asset-yacht.jpg";
import jet from "@/assets/asset-jet.jpg";
import concierge from "@/assets/asset-concierge.jpg";
import hamptons from "@/assets/asset-hamptons.jpg";
import aspen from "@/assets/asset-aspen.jpg";
import beverlyhills from "@/assets/asset-beverlyhills.jpg";
import miami from "@/assets/asset-miami.jpg";
import bugatti from "@/assets/asset-bugatti.jpg";
import rolls from "@/assets/asset-rolls.jpg";
import napa from "@/assets/asset-napa.jpg";
import bombardier from "@/assets/asset-bombardier.jpg";
import westport from "@/assets/asset-westport.jpg";

const btc = (usd: number) => +(usd / 95000).toFixed(2);

export const mockListings = [
  { category_slug: "real-estate", title: "Oceanfront Estate, East Hampton", subtitle: "Shingle-style oceanfront compound", description: "A shingle-style oceanfront compound on 4.2 oceanfront acres with private dune access, twin pools, guest cottage, and a tennis pavilion. Designed by Robert A.M. Stern Architects.", location: "East Hampton, NY", country: "United States", city: "East Hampton", price_usd: 49500000, price_btc: btc(49500000), accepts_btc: true, cover_image: hamptons, gallery: [hamptons, penthouse, villa], featured: true, verified: true },
  { category_slug: "real-estate", title: "Beverly Hills Glass Residence", subtitle: "Contemporary glass residence above Sunset Strip", description: "A contemporary glass residence above the Sunset Strip with 270° views of Los Angeles, infinity pool, screening room, and 8-car subterranean gallery.", location: "Beverly Hills, CA", country: "United States", city: "Beverly Hills", price_usd: 38500000, price_btc: btc(38500000), accepts_btc: true, cover_image: beverlyhills, gallery: [beverlyhills, penthouse], featured: true, verified: true },
  { category_slug: "real-estate", title: "Skyline Penthouse, 432 Park", subtitle: "Full-floor penthouse, 360° Manhattan views", description: "A full-floor penthouse with 360° views of Manhattan, Central Park, and the Hudson. Private elevator, double-height ceilings, and curated interiors.", location: "Manhattan, NY", country: "United States", city: "New York", price_usd: 68000000, price_btc: btc(68000000), accepts_btc: true, cover_image: penthouse, gallery: [penthouse, villa], featured: true, verified: true },
  { category_slug: "real-estate", title: "Slopeside Chalet, Aspen", subtitle: "Ski-in/ski-out timber and stone chalet", description: "Ski-in/ski-out timber and stone chalet on Aspen Mountain with private spa, wine cellar, heated motor court, and direct gondola access.", location: "Aspen, CO", country: "United States", city: "Aspen", price_usd: 32000000, price_btc: btc(32000000), accepts_btc: true, cover_image: aspen, gallery: [aspen, villa], featured: false, verified: true },
  { category_slug: "real-estate", title: "Waterfront Penthouse, Miami Beach", subtitle: "Star Island-adjacent waterfront", description: "Star Island-adjacent waterfront penthouse with private yacht slip, rooftop pool, summer kitchen, and unobstructed Biscayne Bay views.", location: "Miami Beach, FL", country: "United States", city: "Miami Beach", price_usd: 19800000, price_btc: btc(19800000), accepts_btc: true, cover_image: miami, gallery: [miami, westport], featured: false, verified: true },
  { category_slug: "real-estate", title: "Oceanfront Sanctuary Villa", subtitle: "Private 9-bedroom estate on its own peninsula", description: "A private 9-bedroom oceanfront estate on the Florida coast with 35-meter infinity pool, private dock, helipad, and direct Atlantic frontage.", location: "Palm Beach, FL", country: "United States", city: "Palm Beach", price_usd: 24500000, price_btc: btc(24500000), accepts_btc: true, cover_image: villa, gallery: [villa, penthouse, yacht], featured: false, verified: true },

  { category_slug: "cars", title: "Bugatti Chiron Super Sport", subtitle: "Quad-turbo W16 hypercar in Bleu Nuit", description: "Quad-turbo W16 hypercar in bespoke Bleu Nuit over carbon. Delivery mileage, full provenance, U.S. EPA & DOT compliant.", location: "Miami, FL", country: "United States", city: "Miami", price_usd: 4200000, price_btc: btc(4200000), accepts_btc: true, cover_image: bugatti, gallery: [bugatti, lambo], featured: true, verified: true },
  { category_slug: "cars", title: "Rolls-Royce Phantom EWB", subtitle: "Arctic White over Seashell, Privacy Suite", description: "Phantom Extended Wheelbase in Arctic White over Seashell. Privacy Suite, Starlight Headliner, and Bespoke Audio. One owner since new.", location: "Bel Air, CA", country: "United States", city: "Los Angeles", price_usd: 720000, price_btc: btc(720000), accepts_btc: true, cover_image: rolls, gallery: [rolls, ferrari], featured: false, verified: true },
  { category_slug: "cars", title: "Lamborghini Revuelto LP 1015-8", subtitle: "Hybrid V12 hypercar in Nero Aldebaran", description: "Hybrid V12 hypercar finished in Nero Aldebaran with carbon-skin interior. Delivery mileage, full Ad Personam program, U.S. titled and certified.", location: "Beverly Hills, CA", country: "United States", city: "Beverly Hills", price_usd: 1250000, price_btc: btc(1250000), accepts_btc: true, cover_image: lambo, gallery: [lambo, ferrari], featured: true, verified: true },
  { category_slug: "cars", title: "Ferrari 12Cilindri Coupé", subtitle: "Naturally aspirated 6.5L V12 GT", description: "Naturally aspirated 6.5L V12 grand tourer in Rosso Corsa. Tailor Made specification with full Daytona-inspired interior, offered from a U.S. collector.", location: "Scottsdale, AZ", country: "United States", city: "Scottsdale", price_usd: 685000, price_btc: btc(685000), accepts_btc: false, cover_image: ferrari, gallery: [ferrari, lambo], featured: false, verified: true },

  { category_slug: "yachts", title: "Westport W172 Tri-Deck 'Liberty'", subtitle: "American-built 172' composite superyacht", description: "American-built 172' composite tri-deck superyacht. Sky lounge, beach club, on-deck owner's suite, and transatlantic range.", location: "Fort Lauderdale, FL", country: "United States", city: "Fort Lauderdale", price_usd: 58500000, price_btc: btc(58500000), accepts_btc: true, cover_image: westport, gallery: [westport, miami], featured: true, verified: true },
  { category_slug: "yachts", title: "Feadship 95m 'Aurelia'", subtitle: "Custom 95m explorer yacht", description: "Custom 95-meter explorer yacht with helipad, beach club, 8 guest suites, owner's deck with private spa, and global cruising range.", location: "Palm Beach, FL", country: "United States", city: "Palm Beach", price_usd: 215000000, price_btc: btc(215000000), accepts_btc: true, cover_image: yacht, gallery: [yacht, villa], featured: true, verified: true },

  { category_slug: "jets", title: "Bombardier Global 7500", subtitle: "Ultra-long-range flagship, U.S. N-registered", description: "Flagship ultra-long-range jet with four true living spaces, full kitchen, and a permanent bed in the Principal Suite. U.S. N-registered.", location: "Dallas, TX", country: "United States", city: "Dallas", price_usd: 82500000, price_btc: btc(82500000), accepts_btc: true, cover_image: bombardier, gallery: [bombardier, jet], featured: true, verified: true },
  { category_slug: "jets", title: "Gulfstream G700 — Ultra Long Range", subtitle: "Five living areas, master suite", description: "Flagship Gulfstream G700 configured with five distinct living areas, master suite, and the longest range in business aviation.", location: "Savannah, GA", country: "United States", city: "Savannah", price_usd: 78000000, price_btc: btc(78000000), accepts_btc: true, cover_image: jet, gallery: [jet, bombardier], featured: false, verified: true },

  { category_slug: "concierge", title: "Napa Valley Private Harvest Weekend", subtitle: "Estate winery takeover, Michelin chef residency", description: "Four-day private harvest experience: estate winery takeover, Michelin-starred chef residency, helicopter transfers from SFO, and a custom barrel program.", location: "Napa Valley, CA", country: "United States", city: "Napa", price_usd: 145000, price_btc: btc(145000), accepts_btc: true, cover_image: napa, gallery: [napa], featured: false, verified: true },
  { category_slug: "concierge", title: "The Masters — Augusta Patron Suite", subtitle: "Tournament-week hospitality", description: "Tournament-week hospitality: four-day patron badges, private estate accommodation, daily chauffeur, club fittings, and a Champions Dinner reception.", location: "Augusta, GA", country: "United States", city: "Augusta", price_usd: 225000, price_btc: btc(225000), accepts_btc: true, cover_image: concierge, gallery: [concierge], featured: false, verified: true },
  { category_slug: "concierge", title: "Kentucky Derby — Owner's Club Weekend", subtitle: "Four-day, all-access concierge package", description: "Four-day luxury hospitality package with Owner's Club access, private estate accommodations, chef-led dining, bourbon tastings, and chauffeured transfers.", location: "Louisville, KY", country: "United States", city: "Louisville", price_usd: 285000, price_btc: btc(285000), accepts_btc: true, cover_image: concierge, gallery: [concierge], featured: false, verified: true },
];
