/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetIdRouteImport } from './routes/asset.$id'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSellerNewRouteImport } from './routes/_authenticated/seller.new'
import { Route as AuthenticatedSellerIdRouteImport } from './routes/_authenticated/seller.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSellerNewRoute = AuthenticatedSellerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)
const AuthenticatedSellerIdRoute = AuthenticatedSellerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSellerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/asset/$id': typeof AssetIdRoute
  '/seller/$id': typeof AuthenticatedSellerIdRoute
  '/seller/new': typeof AuthenticatedSellerNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/asset/$id': typeof AssetIdRoute
  '/seller/$id': typeof AuthenticatedSellerIdRoute
  '/seller/new': typeof AuthenticatedSellerNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/marketplace': typeof MarketplaceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/asset/$id': typeof AssetIdRoute
  '/_authenticated/seller/$id': typeof AuthenticatedSellerIdRoute
  '/_authenticated/seller/new': typeof AuthenticatedSellerNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/marketplace'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/seller'
    | '/asset/$id'
    | '/seller/$id'
    | '/seller/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/marketplace'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/seller'
    | '/asset/$id'
    | '/seller/$id'
    | '/seller/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/marketplace'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/seller'
    | '/asset/$id'
    | '/_authenticated/seller/$id'
    | '/_authenticated/seller/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AssetIdRoute: typeof AssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seller/new': {
      id: '/_authenticated/seller/new'
      path: '/new'
      fullPath: '/seller/new'
      preLoaderRoute: typeof AuthenticatedSellerNewRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/$id': {
      id: '/_authenticated/seller/$id'
      path: '/$id'
      fullPath: '/seller/$id'
      preLoaderRoute: typeof AuthenticatedSellerIdRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
  }
}

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerIdRoute: typeof AuthenticatedSellerIdRoute
  AuthenticatedSellerNewRoute: typeof AuthenticatedSellerNewRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerIdRoute: AuthenticatedSellerIdRoute,
  AuthenticatedSellerNewRoute: AuthenticatedSellerNewRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MarketplaceRoute: MarketplaceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AssetIdRoute: AssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
