// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getServerConfig() {
  // First try environment variables (Cloudflare)
  const url = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (url && key) {
    console.log('🔵 Server using environment variables for Supabase');
    return { url, key };
  }

  // Check if we're in Cloudflare environment
  const isCloudflare = process.env.CF_PAGES === '1' || process.env.CF_WORKERS === '1';
  
  if (isCloudflare) {
    console.log('🔵 Server using Cloudflare Supabase: sjdocxbywfmzksxyezq');
    return {
      url: 'https://sjdocxbywfmzksxyezq.supabase.co',
      key: process.env.SUPABASE_SERVICE_ROLE_KEY || 'YOUR_CLOUDFLARE_SERVICE_KEY'
    };
  }

  // Lovable fallback
  console.log('🔵 Server using Lovable Supabase: fycahwbrblvrytmkocfk');
  return {
    url: 'https://fycahwbrblvrytmkocfk.supabase.co',
    key: process.env.SUPABASE_SERVICE_ROLE_KEY || 'YOUR_LOVABLE_SERVICE_KEY'
  };
}

function createSupabaseAdminClient() {
  const config = getServerConfig();
  const SUPABASE_URL = config.url;
  const SUPABASE_SERVICE_ROLE_KEY = config.key;

  console.log('✅ Server Supabase admin initialized with URL:', SUPABASE_URL);

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const message = `Missing Supabase environment variable(s).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});