// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Detect environment based on hostname or build mode
function getEnvironmentConfig() {
  const hostname = typeof window !== 'undefined' ? window.location.hostname : '';
  const isLovable = hostname.includes('lovable.app') || hostname.includes('lovable.dev');
  const isCloudflare = hostname.includes('pages.dev') || hostname.includes('fortunecoastalgroup.com');
  const isDevelopment = import.meta.env.DEV || import.meta.env.MODE === 'development';

  // Priority: Environment variables > Hostname detection
  const url = import.meta.env.VITE_SUPABASE_URL || import.meta.env.SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.SUPABASE_PUBLISHABLE_KEY;

  // If explicit env vars are set, use them (Cloudflare)
  if (url && key) {
    return { url, key };
  }

  // Fallback: Lovable uses its own defaults
  if (isLovable || isDevelopment) {
    return {
      url: 'https://fycahwbrblvrytmkocfk.supabase.co',
      key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5Y2Fod2JyYmx2cnl0bWtvY2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0MTI5NzAsImV4cCI6MjA5Nzk4ODk3MH0.tVPXsdtOgDUv4BGywr00F8dJNL-QyP2judHWwvDclWw'
    };
  }

  // Cloudflare fallback
  return {
    url: 'https://sjdocxbywfmzksxyezq.supabase.co',
    key: 'YOUR_CLOUDFLARE_PUBLISHABLE_KEY'
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to hostname detection
  const config = getEnvironmentConfig();
  const SUPABASE_URL = config.url;
  const SUPABASE_PUBLISHABLE_KEY = config.key;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const message = `Missing Supabase environment variable(s).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});